### PR TITLE
Feature/761 build and e2e test ci

### PR DESCRIPTION
**Pull request by skosito**
# Description

Add build and e2e steps to workflow.
Force exit on e2e tests because jest detects this part as open handle:

```
    await new Promise((r) => setTimeout(r, 20000));

```

I think using `--forceExit` flag is ok here.

Also, I used public goerli rpc url for `GOERLI_RPC_URL` env var in workflow, probably better than hiding infura url, as we probably won't get rate limited. The rest of env vars i just copied from `.env.sample` since that is already in the repo.

## Related Issue

#761 

## Motivation and Context

To make PR process more robust.

## How Has This Been Tested

I tested on my fork.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I commit to abide by the Responsibilities of Code Owners/Maintainers.

### CODE REVIEW

**Comment by ognjenkurtic** [comment]
e2e test run logs this: 

_Failed execution of transaction with id 1141cc17-3d96-4cc4-aecb-50e8e4d557ec. Error: NotImplementedException: Not Implemented_

It is because we are invoking storeAnchorHashOnCcsm in the ExecuteVsmCycleCommandHandler.

The test is still green though, i suspect we are not asserting everything we should assert. Could you please open an issue to resolve it separately?

**Comment by ognjenkurtic** [comment]
..and timeout is there to wait for one execution cycle to pass. Open for a better approach.

**Comment by skosito** [comment]
> e2e test run logs this:
> 
> _Failed execution of transaction with id 1141cc17-3d96-4cc4-aecb-50e8e4d557ec. Error: NotImplementedException: Not Implemented_
> 
> It is because we are invoking storeAnchorHashOnCcsm in the ExecuteVsmCycleCommandHandler.
> 
> The test is still green though, i suspect we are not asserting everything we should assert. Could you please open an issue to resolve it separately?

yea i assumed you are aware of this and it is some tmp not implemented thing, as this is also showing locally, i will open separate issue for that

regarding timeout, i understand why its there, but jest sees it as some handler that is hanging, and after tests are green, jest hangs with message that there is something not closed, and i identified it is that part, so i added --forceExit so github worklow doesnt hang

but i will include this in that separate issue i open, for now i dont think it should block merge of this PR. what do you think?

**Comment by Ybittan** [comment]
@ognjenkurtic can you please review Skos' comment to unblock this PR?

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by Kasshern — APPROVED** [review]

**Pull request merged**
