### PR TITLE
Restructure examples in a non-destructive way

### PR DESCRIPTION
**Pull request by kthomas**
This proposal attempts to accomplish the goals of https://github.com/eea-oasis/baseline/pull/415 without breaking third-party links to `examples/**/*`.

@ognjenkurtic @skosito @humbitious

### CODE REVIEW

**Comment by fosgate29** [comment]
Approved

**Review by ognjenkurtic — APPROVED** [review]

**Review by fosgate29 — APPROVED** [review]
Approved

**Comment by ognjenkurtic** [comment]
@kthomas please resolve the conflict so that we can merge this one

**Comment by ognjenkurtic** [comment]
@kthomas please resolve and merge until end of next week. I will be closing the PR afterwards.

**Pull request closed without merging**
