### PR TITLE
Revert "Merge pull request #415 from skosito/add-ref-implementations-…

### PR DESCRIPTION
**Pull request by kthomas**
Sorry for not calling this out earlier, but it just dawned on me that https://github.com/eea-oasis/baseline/pull/415 breaks tons of inbound links to the repo.

We should have a short discussion to come up with a different way to make this work without breaking all of those links ;)

I complained about it on @skosito's original PR after it was merged here: https://github.com/eea-oasis/baseline/pull/415#issuecomment-976572041

### CODE REVIEW

**Comment by kthomas** [comment]
Any solution that leads to `examples/bri/**/*` resolving is fine by me of course. But then, this new folder structure (empty examples folder) needs another discussion.

Sorry for not thinking of this before it was merged :D

For SEO's sake, though I am certainly no SEO expert, I don't think you really want to break any links or change them without proper 301s... (aka work!) Do you want to do all of that work? I surely don't :D

I recall many third-party links to the `examples/**/*` paths. Please simply approve/merge this PR to maintain integrity of links and let's come up with a different way of renaming/structuring stuff yeah?

**Comment by skosito** [comment]
> Any solution that leads to `examples/**/*` resolving is fine by me of course. But then, this new folder structure (empty examples folder) needs another discussion.
> 
> Sorry for not thinking of this before it was merged :D
> 
> For SEO's sake, though I am certainly no SEO expert, I don't think you really want to break any links or change them without proper 301s... (aka work!) Do you want to do all of that work? I surely don't :D
> 
> I recall many third-party links to the `examples/**/*` paths. Please simply approve/merge this PR to maintain integrity of links and let's come up with a different way of renaming/structuring stuff yeah?

This makes sense, but I am not sure I have permissions to approve and merge PRs.

Also please check my reply on original PR, I am just curious how much links are there around the web that we don't have control over to go and change them, since the only one I found is in baseline docs, still referencing bri-1-privacy branch (therefore outdated before this change), could you please post couple of examples of such 3rd party libraries/articles/documentation referencing examples/bri-1 folder directly?
To me would be more logical to have links to repo main page instead of specific folders, since folders structure is often subject to change, and should not be set in stone and impossible to move around.
Also, based on quick googling, I am not sure I found some easy way to do this redirecting, but can take further look...

Regarding empty examples folder, was not my idea, but I believe purpose is to show there are no examples currently, but couple of coming with core devs working groups.

**Comment by kthomas** [comment]
Makes sense to consider a new structure. But this PR should be reverted. One broken link is one too many. There are _many_, in many places.

**Comment by kthomas** [comment]
@skosito you should have permission to approve it, although we will need @skarred14 for a second.

**Comment by skosito** [comment]
> Makes sense to consider a new structure. But this PR should be reverted. One broken link is one too many. There are _many_, in many places.

Thanks for answer, if there are many places then it is better to revert I guess.

The only reason I brought this up is that you mentioned SEO, and I can not find single such link by googling around, that's why I was curious to see couple examples, if you find some please post them in PR description, I am sure it would be beneficial for future reference.

My argument was that if they are on places we can easily edit (baseline docs, provide docs, your medium articles) we can simply do that in matter of minutes, without having to think about redirect mechanism. I found bri-1 inconsistency that can cause confusion in documentation that was not addressed before.

Since I am not official maintainer of project I will not be able to approve because I want to follow the rules, please remove me from reviewers list. Thanks.

**Comment by kthomas** [comment]
> > Makes sense to consider a new structure. But this PR should be reverted. One broken link is one too many. There are _many_, in many places.
> 
> Thanks for answer, if there are many places then it is better to revert I guess.
> 
> The only reason I brought this up is that you mentioned SEO, and I can not find single such link by googling around, that's why I was curious to see couple examples, if you find some please post them in PR description, I am sure it would be beneficial for future reference.

Here is a good example -- this article has at least one link to BRI-2 examples: https://cointelegraph.com/news/baseline-protocol-unveils-ethereum-interoperability-deployment-will-take-time

There are many more articles like this one. Not sure how you are searching for those links, but GitHub is insanely popular :D ...so I think Google may treat it differently-- and this is another very important reason for merging this PR without delay. And it may be the reason you aren't able to readily find the links. Trust me, they are everywhere :P

> My argument was that if they are on places we can easily edit (baseline docs, provide docs, your medium articles) we can simply do that in matter of minutes, without having to think about redirect mechanism. I found bri-1 inconsistency that can cause confusion in documentation that was not addressed before.

Sure, this makes sense. Perhaps there is a better way to do it. I was just going for fastest possible win, since the links are literally broken as of right now ;)

> Since I am not official maintainer of project I will not be able to approve because I want to follow the rules, please remove me from reviewers list. Thanks.

I simply seek your approval since it was your PR... nothing personal :)

**Comment by skosito** [comment]
> > > Makes sense to consider a new structure. But this PR should be reverted. One broken link is one too many. There are _many_, in many places.
> > 
> > 
> > Thanks for answer, if there are many places then it is better to revert I guess.
> > The only reason I brought this up is that you mentioned SEO, and I can not find single such link by googling around, that's why I was curious to see couple examples, if you find some please post them in PR description, I am sure it would be beneficial for future reference.
> 
> Here is a good example -- this article has at least one link to BRI-2 examples: https://cointelegraph.com/news/baseline-protocol-unveils-ethereum-interoperability-deployment-will-take-time
> 
> There are many more articles like this one. Not sure how you are searching for those links, but GitHub is insanely popular :D ...so I think Google may treat it differently-- and this is another very important reason for merging this PR without delay. And it may be the reason you aren't able to readily find the links. Trust me, they are everywhere :P
> 
> > My argument was that if they are on places we can easily edit (baseline docs, provide docs, your medium articles) we can simply do that in matter of minutes, without having to think about redirect mechanism. I found bri-1 inconsistency that can cause confusion in documentation that was not addressed before.
> 
> Sure, this makes sense. Perhaps there is a better way to do it. I was just going for fastest possible win, since the links are literally broken as of right now ;)
> 
> > Since I am not official maintainer of project I will not be able to approve because I want to follow the rules, please remove me from reviewers list. Thanks.
> 
> I simply seek your approval since it was your PR... nothing personal :)

Thanks for the link, wonder why I could not find it.
No no, of course it is nothing personal, I just understand only officially voted maintainers can approve PRs, I simply thought I don't have permission :). But sure, here is approval from my side. Thanks for bringing this up.

**Review by skosito — APPROVED** [review]

**Review by caleteeter — APPROVED** [review]

**Comment by humbitious** [comment]
The new folder structure is important, and we've had this out for a long time. There was ample opportunity to  review and get this right.  I'm not in favor of reverting.

**Review by humbitious — CHANGES_REQUESTED** [review]
Reverting should be discussed. I'm not in favor.

**Comment by kthomas** [comment]
> Reverting should be discussed. I'm not in favor.

Overruled this time.

**Comment by humbitious** [comment]
> > Reverting should be discussed. I'm not in favor.
> 
> Overruled this time.

I'm pushing it again, if it reverts. Provide doesn't get to simply "overrule."  Make your case in discussion in a timely way, or this happens.

**Comment by kthomas** [comment]
> > > Reverting should be discussed. I'm not in favor.
> > 
> > 
> > Overruled this time.
> 
> I'm pushing it again, if it reverts. Provide doesn't get to simply "overrule." Make your case in discussion in a timely way, or this happens.

<3 I fully understand this and look forward to having a quick review to do what's best for the structure of the repo.

This community, IMHO, should look out for each other... did anyone consider the inbound links AT ALL in the making of that PR? I had reviewed it but not approved either... I am just a little amazed that all that rich inbound content matters not to you.

We want to get ADOPTION here!! Why would we cripple that right?

Thanks John, see you soon.

**Review by skarred14 — APPROVED** [review]

**Comment by kthomas** [comment]
Closing as these changes made it in via https://github.com/eea-oasis/baseline/pull/427

**Pull request closed without merging**
