### PR TITLE
Feature/746 efficient signature verification

### PR DESCRIPTION
**Pull request by biscuitdey**
# Description

There are a number of challenges to implementing ECDSA signature algorithms in zkSNARKs.

1. zkSNARK proving systems generally use specific elliptic curves (edwards, bn128, alt_bn128) that only allow operations on numbers represented as residues modulo a specific prime. This limits the maximum "register size" for numbers used in zkSNARK proofs to 254 bits. However, networks like Ethereum and Bitcoin use the Elliptic Curve Digital Signature Algorithm (ECDSA) and the secp256k1 curve, a NIST-standard curve that is not "SNARK-friendly." Operations on secp256k1 elliptic curve points involve arithmetic on 256-bit numbers, which would overflow the 254-bit registers allowed in today's SNARK systems. Implementing ECDSA algorithms inside requires us to build ZK circuits for BigInt arithmetic and secp256k1 operations using 254-bit registers; essentially, we must perform "non-native field arithmetic."

2. Certain options such as the [circom-ecdsa](https://github.com/0xPARC/circom-ecdsa), which implement "non-native field arithmetic" for performing ECDSA signature verification, have long trusted setup time, long circuit compilation time, large proving key sizes, etc.

## Comparisons

_Circom-ECDSA: Groth16 on a 20-core 3.3GHz, 64G RAM_

_Spartan-ECDSA: SpartanNIZK on a 10-core M1 MacBook Pro, 16GB RAM_

|                                                                                               | circom-ecdsa  | spartan-ecdsa |
| --------------------------------------------------------------------------------------------- | ------------- | ------------- |
| ZKSnark Protocol                                                                              | Groth16       | SpartanNIZK   |
| Curve used                                                                                    | BN128         | Secq256k1     |
| Constraints                                                                                   | 9480361       | 8,076         |
| Powers of Tau Ceremony ( Available curves -> bn128, bls12-381; Number of constraints -> 2^21) | several hours | Not needed    |
| Circuit compilation                                                                           | 324s          | 5s            |
| Witness generation                                                                            | 150s          | 3s            |
| Trusted setup phase 2 key generation                                                          | 5569s         | Not needed    |
| Trusted setup phase 2 contribution                                                            | 767s          | Not needed    |
| Proving key size                                                                              | 5.8GB         | Not needed    |
| Proving key verification                                                                      | 6211s         | Not needed    |
| Proving time                                                                                  | 239s          | 2s            |
| Verification time                                                                             | <1s           | 300ms         |
| Proof size                                                                                    | 128bytes      | 16kb          |

Sources:

- Circom-ecdsa: [1](https://0xparc.org/blog/zk-ecdsa-1) , [2](https://github.com/0xPARC/circom-ecdsa) , [3](https://github.com/iden3/snarkjs)
- Spartan-ecdsa: [4](https://personaelabs.org/posts/spartan-ecdsa/) , [5](https://eprint.iacr.org/2019/550.pdf) , [6](https://github.com/personaelabs/spartan-ecdsa)

Reasons for not using PLONK:

Although PLONK doesn't require a trusted setup per application-specific circuit, it does require the powers of tau ceremony._[7](https://blog.iden3.io/circom-snarkjs-plonk.html)_ Ptau is only available for BN128 and BLS12-381 curves, making it incompatible with fast circuits that use Secq256k1 curve._[8](https://github.com/iden3/snarkjs)_

**Spartan-ECDSA has been chosen because it is the fastest and most efficient zk-SNARK protocol for ECDSA signature verification circuits.**

## Spartan-ECDSA

- Based on the Spartan Non-Interactive Zero-knowledge Proof (SpartanNIZK)
- Fastest open-source method to verify secp256k1 ECDSA signatures
- Doesn’t require a trusted setup
- In the case of ECDSA verification, can work on elliptic curve where discrete log holds

Article/Research paper: [9](https://personaelabs.org/posts/spartan-ecdsa/) , [10](https://eprint.iacr.org/2019/550.pdf)
Github: [11](https://github.com/personaelabs/spartan-ecdsa)

## Related Issue

#746 

## Motivation and Context

Need to have efficient ECDSA signature verification in each circuit

## How Has This Been Tested

Unit test has been added (after adding required artifacts)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I commit to abide by the Responsibilities of Code Owners/Maintainers.

### CODE REVIEW

**Comment by Therecanbeonlyone1969** [comment]
@biscuitdey I hear you. Spartan is not widely used and will present interoperability issues. There is a simpler solution to this where we can continue to snarkjs and PLONK. Rather than ECDSA signatures, we use [EdDSA signatures using the twisted Edwards curve (BabyJubJub)](https://github.com/iden3/circomlib/blob/master/circuits/eddsa.circom). Also in [snarkjs](https://github.com/iden3/go-iden3-crypto)

When we generate a DID we just add the pubKey of the BabyJubJub curve into the DID doc, besides a secp256k1 pubKey to sign transaction to be put onchain.

Thoughts?

cc @ognjenkurtic @Kasshern @Ybittan

**Comment by ognjenkurtic** [comment]
> If we decide to use EdDSA signatures, then this PR wouldn't be required and I'll change the circuits to use the EdDSA verifier available in the circomlib. Also, we'd need to update the signatures we are using throughout the application.

28.9.2023 - SRI sync call - We agreed to take this approach. We ll expect  EdDSA key format everywhere in the app

**Comment by ognjenkurtic** [comment]
@biscuitdey @ognjenkurtic to open issues for the client, circuit and auth.

**Comment by biscuitdey** [comment]
Decided to use Eddsa signature verification

**Pull request closed without merging**
