### PR TITLE
adding battleship folder

### PR DESCRIPTION
**Pull request by Manik-Jain**
# Description

Adding `/example/battleship` and branch `battleship`

## Related Issue

https://github.com/eea-oasis/baseline-blips/issues/7

## Motivation and Context

This will help the development for BLIP-7

## Checklist

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ognjenkurtic — COMMENTED** [review]
Is the license correct? Bri-1 and 2 examples are using "license": "CC0 1.0 Universal".

**Comment by Manik-Jain** [comment]
> Is the license correct? Bri-1 and 2 examples are using "license": "CC0 1.0 Universal".

Verison changed to `CC0 1.0 Universal`

**Comment by GoldenBit0** [comment]
This PR will be a draft until there is code behind it.

**Review by fosgate29 — APPROVED** [review]
Approved

**Comment by ognjenkurtic** [comment]
@Manik-Jain @fosgate29 what is the status of this one now that we have battleship implemented and merged? Can we close it?

**Comment by Manik-Jain** [comment]
Closing this PR, as other PR for battleship has been merged.

**Pull request closed without merging**
