### PR TITLE
#620 - correct some language in BRI-3 readme

### PR DESCRIPTION
**Pull request by fleischr**
# Description

BRI-3 readme contains some confusing / misleading language. This PR removes it.

## Related Issue

See issue #620 

## Motivation and Context

Keep documentation focused and clear

## How Has This Been Tested

Doc change only

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] I commit to abide by the Responsibilities of Code Owners/Maintainers.

### CODE REVIEW

**Comment by Ybittan** [comment]
Given that BRI1 has provide technology deeply embedded into it (example: "This implementation of the Baseline Protocol leverages the Provide stack for security"), and even has its readme titled "shuttle-app", is it really fair to call it vendor-agnostic?

**Review by skosito — CHANGES_REQUESTED** [review]
yes, this is first vendor agnostic implementation, not developed by any company or tied to any company, what is incorrect there?

from your issue:
```
This may mislead some to think they cannot run BRI-1/PRVD or other prior BRIs in a permissionless, open source way.
```
Never in readme was mentioned that this is the only permissionless, open source implementation. 

not sure about basis for baseline SDK part, and if it's planned to build upon it, we can maybe change to "might be used as basis for baseline sdk" because there is no plan yet for sdk, but can double check

can be discussed on a core dev call and with bri-3 team, until then not approving

**Comment by fleischr** [comment]
> Given that BRI1 has provide technology deeply embedded into it (example: "This implementation of the Baseline Protocol leverages the Provide stack for security"), and even has its readme titled "shuttle-app", is it really fair to call it vendor-agnostic?

BRI-1 was made vendor agnostic at the time its repos were open sourced and included to the PRVD Oasis charter. All aspects essential to running the BRI-1 implementation can be achieved independent to Provide Technologies Inc. In many cases, migration of the repos to PRVD has in fact required the removal of references to the Provide commercial infrastructure. There was significant effort and expense taken on to achieve this that ought be better understood. This is why I examine the claim of BRI-3 being the _first_ vendor-agnostic implementation of the standard debatable and misleading.

Overall, the term "vendor agnostic"  isn't a helpful distinction to make between one BRI to another when they are all open sourced in a similar manner. Particularly if it implies other BRIs *aren't* open sourced when in fact they are. This is why I recommend we stop using the term "vendor agnostic"

FYI -While Shuttle is a major enabler to BRI-1/PRVD, its not required.

**Comment by Ybittan** [comment]
> FYI -While Shuttle is a major enabler to BRI-1/PRVD, its not required.

To me personally, as long as there is reference at all to Provide Technologies Inc. (or any other vendor) in the code and in the readme, it is not vendor agnostic. This is a helpful distinction for a new user, as there are pros and cons to utilizing reference material built by a vendor with their stack in mind. It's not a bad thing, and to the right user, it's a good thing, but it is something that needs to be made clear. 

Things like "FYI -While Shuttle is a major enabler to BRI-1/PRVD, its not required." is an immediate indication to me that it is not vendor agnostic. Out of the box, there should be no reference whatsoever to any commercial entity(ies) for it to be vendor agnostic. Again, in my opinion.

**Comment by fleischr** [comment]
@Ybittan @skosito Disappointed that we can't be better aligned on this, but understand your objections.  Would still recommend more neutral language to be used here. If you think of different verbiage you'd like to use, I'd be happy to check it out later.

I'll close this PR for now to prevent the thread from going too far OT.

**Pull request closed without merging**
