### PR TITLE
Bpi interop/create bri1 msg example

### PR DESCRIPTION
**Pull request by fleischr**
# Description

Documents how to create the BPI Vendor Bank Verification use case on BRI-1 via Provide Shuttle, Postman, Node.js, and SAP ABAP

## Related Issue

#695 

## Motivation and Context

Supports the BPI Interoperability showcase and roadshow

## How Has This Been Tested

included in the readme provided

## Screenshots (if appropriate)

included in the readme provided

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation. N/A
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I commit to abide by the Responsibilities of Code Owners/Maintainers.

### CODE REVIEW

**Comment by fleischr** [comment]
Any feedback on this PR?

**Comment by Therecanbeonlyone1969** [comment]
> Any feedback on this PR?

@fleischr we discussed that we need the example of NATS-to-NATS and not Client-NATS. So this PR needs to be updated accordingly, IMHO.

**Comment by Therecanbeonlyone1969** [comment]
@fleischr can you open a new PR with just NATS message json schemas please. Just the base schemas BRI-1 uses. We can work with that.

**Comment by fleischr** [comment]
Also see https://github.com/provideplatform/axiom/issues/96

**Comment by ognjenkurtic** [comment]
@fleischr We ll reopen this one once the usage of did-jwt in BRI-1 has been settled.

**Comment by fleischr** [comment]
@ognjenkurtic @Therecanbeonlyone1969 any other feedback on the PR otherwise? Are there any other details apart from did-jwt bring requested?

**Comment by Therecanbeonlyone1969** [comment]
> @ognjenkurtic @Therecanbeonlyone1969 any other feedback on the PR otherwise? Are there any other details apart from did-jwt bring requested?

@fleischr besides the message schemas we discussed. No. Just did-jwt.

**Comment by fleischr** [comment]
Could you add the did-jwt requirements here to #695 ? This will help me reopen the PR later as needed

**Comment by fleischr** [comment]
@ognjenkurtic I would like you to give me a heads up next time you want to close one of my PRs without merging

**Pull request closed without merging**
